VirtuslabRnD/pulumi-kotlin

README.md

Remove outdated video (demo) from README.md

---

src/main/resources/version-config.json

Resolves: None
This PR replaces the released versions with SNAPSHOT versions.

Prepare for next development phase

---

.github/workflows/compile_and_test.yml
.github/workflows/e2e_tests.yml
.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
src/main/resources/version-config.json

Resolves: None
This PR adds `workflow_dispatch` as a CI trigger.

Add workflow dispatch

---

src/main/resources/version-config.json

Resolves: None
This release includes the following versions:
cloudflare/v4.15.0.1
slack/v0.3.1.1
github/v5.4.0.1
random/v4.11.2.1
gcp/v6.49.0.1
google-native/v0.28.0.1
aws/v5.29.1.1
aws-native/v0.47.0.1
azure/v5.35.0.1
azure-native/v1.93.0.1
kubernetes/v3.24.0.1
nomad/v0.4.0.1
docker/v3.6.1.1
gitlab/v4.9.0.2
digitalocean/v4.18.0.1
alicloud/v3.31.0.1

Prepare release

---

.github/workflows/e2e_tests.yml
.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
build.gradle.kts

Resolves: None
As per https://github.com/jeremymailen/kotlinter-gradle/issues/315#issuecomment-1468436990. This should help us get rid of the overwhelming formatting logs.

Disable logs in publication tasks

---

README.md
build.gradle.kts
buildSrc/src/main/kotlin/ReleaseScripts.kt

Resolves: #197
Improve docs for Gradle

Improve docs for Gradle

---

examples/azure-native-sample-project/src/main/kotlin/project/Main.kt
examples/azure-sample-project/src/main/kotlin/project/Main.kt
src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/resources/ResourceGenerator.kt

Resolves: #187 
This PR fixes issues with no-args resources.

Fix creating resource with just the name

---

README.md
examples/azure-native-sample-project/src/main/kotlin/project/Main.kt
examples/azure-sample-project/src/main/kotlin/project/Main.kt
examples/gcp-provider-sample-project/src/main/kotlin/project/Main.kt
examples/gcp-sample-project/src/main/kotlin/project/Main.kt
examples/google-native-sample-project/src/main/kotlin/project/Main.kt
examples/kubernetes-sample-project/src/main/kotlin/project/Main.kt
src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/resources/ResourceGenerator.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/CodegenTest.kt

Resolves: #190 
This PR removes the `resource` keyword from resource functions.

Remove resource keyword from resource functions

---

.github/workflows/prepare_release.yml

Resolves: None
Right now the cleanup step is failing: https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/5541850249/jobs/10115920666

Add condition to prepare_release.yml

---

src/main/kotlin/org/virtuslab/pulumikotlin/codegen/sdk/Common.kt

Add extension function for Context#export

---

examples/azure-native-sample-project/README.md
examples/azure-sample-project/README.md
examples/gcp-provider-sample-project/README.md
examples/gcp-sample-project/README.md
examples/google-native-sample-project/README.md
examples/kubernetes-sample-project/README.md

Add readmes to example projects

---

.github/workflows/prepare_release.yml
.github/workflows/update_schemas.yml

Resolves: None
Right now our PRs are opened by the Pulumi Kotlin bot, but the commits in those PRs are made by the GitHub Actions bot. In this PR I set the committer to be the Pulumi Kotlin bot. See: https://stackoverflow.com/a/74071223/12464594

Use Pulumi Kotlin bot to make commits from CI

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
build.gradle.kts
buildSrc/src/main/kotlin/SchemaMetadata.kt
buildSrc/src/main/kotlin/code-generation.gradle.kts
src/main/resources/version-config.json

Support multiple versions of one provider

---

README.md
build.gradle.kts
buildSrc/src/main/kotlin/ReleaseScripts.kt
buildSrc/src/test/kotlin/ReleaseScriptsTest.kt
buildSrc/src/test/resources/README-after-generator-update.md
buildSrc/src/test/resources/README-after-schema-update.md
buildSrc/src/test/resources/README-before-generator-update.md
buildSrc/src/test/resources/README-before-schema-update.md

Resolves: #275 
The table in the readme will get updated automatically with each release.

Automate README updates

---

sdk/build.gradle.kts

Resolves: None
This is the release of pulumi-kotlin/v0.9.4.0.

Release common library

---

.github/workflows/compile_and_test.yml
.github/workflows/e2e_tests.yml
.github/workflows/prepare_release.yml
.github/workflows/publish_sdk.yml
.github/workflows/publish_to_maven_local.yml
.github/workflows/update_schemas.yml

Resolves: None
Jobs are failing in this PR: https://github.com/VirtuslabRnD/pulumi-kotlin/pull/456

Update GitHub Action versions

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
src/main/resources/version-config.json

Resolves: #557 
This PR adds a provider for Keycloak.

Add Keycloak provider

---

build.gradle.kts
buildSrc/src/main/kotlin/code-generation.gradle.kts
src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step2intermediate/IntermediateRepresentationGenerator.kt
src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/resources/ResourceGenerator.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/CodegenTest.kt

Resolves: #566
This is a continuation of #567. This should stop failing tests once the new SDK is released. I'm

Update code generation to support resource components

---

src/main/resources/version-config.json

Add new Pulumi Gitlab major

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
I forgot to update GH Actions.

Add new Gitlab major to pipeline

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
src/main/resources/version-config.json

Add Pulumi Vault provider

---

.github/workflows/compile_and_test.yml
.github/workflows/e2e_tests.yml
.github/workflows/prepare_release.yml
.github/workflows/update_schemas.yml
README.md
build.gradle.kts
buildSrc/src/main/kotlin/code-generation.gradle.kts
examples/google-native-sample-project/pom.xml
sdk/src/test/kotlin/com/pulumi/kotlin/options/ResourceOptionsTest.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/CodegenTest.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/CodeGeneratorGenerateFunctionsTest.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/CodeGeneratorGenerateTypesTest.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/KDocGeneratorTest.kt

Resolves: None
This PR updates the common SDK dependency in provider dependencies.

Update common SDK dependency

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
.github/workflows/update_schemas.yml
buildSrc/src/main/kotlin/ReleaseScripts.kt
src/main/resources/version-config.json

Resolves: None
This PR adds a Gitlab v8 major and makes some cosmetic fixes.

Add new Gitlab major

---

src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step1schemaparse/SchemaModel.kt

Resolves: None
See: https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/9886479544/job/27312016486

Add `plain` field in StringProperty

---

src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step1schemaparse/SchemaModel.kt

Resolves: None
See relevant Actions run: https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/10317285774/job/28561246486

Add `overlaySupportedLanguages` field in Resource

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
examples/gcp-provider-sample-project/pom.xml
examples/gcp-sample-project/pom.xml
examples/kubernetes-sample-project/pom.xml
src/main/resources/version-config-e2e.json
src/main/resources/version-config.json

Add new majors for GCP and Azure

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
src/main/resources/version-config.json

Resolves: None
Version `1.0.0` of `aws-native` has been released.

Add new aws-native major
