.github/workflows/e2e_tests.yml
examples/google-native-sample-project/Pulumi.example.yaml

Resolves: None
Since we don't build the whole schema in E2E tests anymore, these tests can be run using GitHub shared runners.

Move E2E tests to GitHub runner

---

.github/workflows/e2e_tests.yml
examples/azure-native-sample-project/src/main/kotlin/project/Main.kt
examples/azure-sample-project/src/main/kotlin/project/Main.kt
src/e2e/kotlin/com/virtuslab/pulumikotlin/azure/AzureTestUtils.kt

Resolves: https://github.com/VirtuslabRnD/jvm-lab/issues/87
I updated the configuration to run on the VirtusLab Azure subscription. **Note**: the `Basic_A0` VM size was not available for our subscription.

Update Azure authentication config

---

README.md
buildSrc/src/test/kotlin/ReleaseScriptsTest.kt

Resolves: #151 
Improvements after feedback in https://github.com/VirtuslabRnD/pulumi-kotlin/pull/199.
- consistent usage of snake case in settings.xml example
- warn that docs only include Java SDK example snippets
- convert long inline links into reference links
Merge only after https://github.com/VirtuslabRnD/jvm-lab/pull/82 is merged (so that workflows running after merges to `main` are green).

Improve README.md after feedback in #199

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Related to task [Create autoscaled pool for CI/CD on GCP](https://github.com/VirtuslabRnD/jvm-lab/issues/52) and [corresponding internal PR](https://github.com/VirtuslabRnD/jvm-lab/pull/82). 
This PR adds label `active` to self-hosted workflows.
This label is used by CI/CD mechanisms on GCP Cloud Functions in order to properly unregister runners and shutdown virtual machines.
Runners with label `active` are protected against deletion when multi-job workflows have still pending jobs and can assign them to a runner.

Add `active` label to self hosted workflows

---

README.md
src/main/resources/version-config.json

Resolves: None
This PR adds two commits that are missing after a manual release that was made from my computer. These commits should be merged with the "Rebase and merge" strategy instead of "Squash and merge", because we want to tag the first commit and we only want to trigger CI for the second commit.

Release Pulumi Random to Maven Central

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
This way publications go through (see: https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/4226558228 and https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/4226564812).

Disable Gradle daemon in publications

---

.github/workflows/prepare_release.yml

Resolves: None
Right now we try to publish snapshot versions to Maven Central. This doesn't do anything, as this step in Gradle is disabled for SNAPSHOT versions, but we still build the jars on CI/CD, which isn't necessary and wastes resources. Also, we needlessly upload documentation to the GCP bucket.

Disable attempts to publish snapshots to Maven Central

---

.github/workflows/e2e_tests.yml

Resolves: None
We were getting warnings about `pulumi/setup-pulumi@v2` being deprecated.

Update deprecated Pulumi GH action

---

src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step2intermediate/PulumiName.kt
src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/resources/ResourceGenerator.kt
src/main/kotlin/org/virtuslab/pulumikotlin/codegen/utils/StringUtils.kt
src/test/kotlin/org/virtuslab/pulumikotlin/TestUtils.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/CodegenTest.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/step2intermediate/PulumiNameTest.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/utils/StringUtilsKtTest.kt
src/test/resources/schema-gcp-classic-6.59.0-with-acronym-in-resource-name.json

Resolves: #221 
`IAMBinding` -> `iamBinding`
`IamAuditConfig` -> `iamAuditConfig`
`OrganizationPolicy` -> `organizationPolicy`
This one is a bit awkward, but it's not our fault they called it `VMware` instead of `Vmware`:
`VMwareCluster` -> `vMwareCluster`

Improve acronym function names

---

README.md

Resolves: None
Add some logos to our README.md to make it more visually pleasing.
See [preview](https://github.com/VirtuslabRnD/pulumi-kotlin/tree/add-logos-to-readme).

Add logos of Pulumi, Kotlin and VirtusLab to README.md

---

.github/workflows/publish_sdk.yml
.github/workflows/publish_to_maven_local.yml
sdk/build.gradle.kts
sdk/src/main/kotlin/com/pulumi/kotlin/Common.kt
sdk/src/main/kotlin/com/pulumi/kotlin/PulumiNullFieldException.kt
sdk/src/main/kotlin/com/pulumi/kotlin/ResourceMapping.kt
sdk/src/main/kotlin/com/pulumi/kotlin/options/Alias.kt
sdk/src/main/kotlin/com/pulumi/kotlin/options/CustomResourceOptions.kt
sdk/src/main/kotlin/com/pulumi/kotlin/options/CustomTimeouts.kt
sdk/src/main/kotlin/com/pulumi/kotlin/options/ResourceTransformation.kt
settings.gradle.kts

Resolves: #41 
This PR is the first step. After manually releasing the SDK (by _manually_ I mean through a CI job triggered through workflow dispatch), tagging it, and updating its version to SNAPSHOT again, we'll need another PR that would remove the built-in classes and replace them with a dependency (which should be quite easy to do, I already tested it out). I think there's no point in automating anything at this point, especially if we want to fix this bug before we release the article (+ I don't expect these files to change too much, so it shouldn't be too painful).

Extract shared classes to a separate SDK

---

README.md
src/main/resources/version-config.json

Resolves: None
This release includes the following versions:
cloudflare/v4.16.0.1
cloudflare/v5.5.0.1
slack/v0.4.2.1
github/v5.16.0.1
random/v4.13.2.1
gcp/v6.64.0.1
google-native/v0.31.1.1
aws/v5.42.0.1
aws-native/v0.73.1.1
azure/v5.48.1.1
azure-native/v1.104.0.1
azure-native/v2.4.0.1
kubernetes/v3.30.2.1
kubernetes/v4.1.1.1
nomad/v0.4.1.1
docker/v3.6.1.2
docker/v4.3.0.1
gitlab/v4.10.0.1
gitlab/v5.0.2.1
gitlab/v6.1.0.1
digitalocean/v4.21.0.1
alicloud/v3.43.0.1
The reason for this release is for all the libraries to rely on the common `pulumi-kotlin` SDK from now on.

Release provider libraries

---

buildSrc/src/main/kotlin/ReleaseScripts.kt
buildSrc/src/main/kotlin/code-generation.gradle.kts

Resolves: None
The recent failures seem to be related to GH issues, but I still want to use this opportunity to update our timeout&retry configuration.

Increase timeout and retry limit

---

src/main/resources/version-config.json

Resolves: None
A new major version appeared for AWS. **Note**: there's also version `6.0.0` available on Maven Central, but there's no schema tagged for that one, so we have to skip it.

Add new AWS major

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
Publication to Maven Local has been flaky for the past few days and I want to verify if it's due to networking issues on GitHub Actions or something else.

Persist buildSrc test reports in case of failure

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
I forgot to add them [here](https://github.com/VirtuslabRnD/pulumi-kotlin/pull/449). Will do the three missing releases manually.

add missing providers to GH actions

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
Node 20 doesn't work on our self-hosted runners. We would need to make updates to the config of those machines, for now I'm downgrading. It works on the default `ubuntu-latest` machines, so I'm only downgrading some stuff.

Downgrade version of actions in self-hosted jobs

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
Artifact upload is failing in jobs run on self-hosted runners.

Downgrade upload-artifact action in jobs run on a self-hosted runner

---

src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/KDocGenerator.kt
src/test/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/KDocGeneratorTest.kt

Resolves: #511 
This PR filters out lines with empty markdown header tags.

Fix docs generation

---

sdk/src/main/kotlin/com/pulumi/kotlin/Tuples.kt
sdk/src/test/kotlin/com/pulumi/kotlin/TuplesTest.kt

Resolves: #394 
For this to become available we'll need a new release of the core SDK + new releases of all versions. A core SDK release is in order anyway, because we're on `0.9.4` and there's three newer versions after that. **Note**: unfortunately, the fields inside tuples are marked with `@Nullable` in Java, so we had to make them nullable as well.

Add destructing extension functions for tuples

---

src/main/kotlin/org/virtuslab/pulumikotlin/codegen/step3codegen/types/TypeGenerator.kt

Related to: #402
This is absolutely not a fix, however no one will have the time to actually fix this any time soon and right now there is no way to use functions such as this one (we immediately get a NPE in `toKotlin`). It's actually a great fear of mine that one of the libraries that I use in my demo presentations will break like this 🙈 The actual fix will presumably be to make all fields lazy and only report errors once they're touched by the user. With this workaround we will at least have a way to make a function/resource work after someone reports such a problem in one of the providers.

Add a workaround for nulls in non-nullable fields

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: #513
I managed to update the version of runners + CentOS, see related PR: https://github.com/VirtuslabRnD/jvm-lab/pull/120 (I already used `pulumi up` on it). You can see a trial run with updated versions here: https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/9339671477

Update GitHub action versions

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
Old provider majors never get their schema updated, but nevertheless we build them all the time wasting GCP resources.
I also made a change where less memory-intensive providers will build on default GitHub runners.

Remove old provider versions from Actions

---

.github/workflows/prepare_release.yml
.github/workflows/rclone.conf
build.gradle.kts
examples/azure-native-sample-project/pom.xml
examples/azure-sample-project/pom.xml
examples/azure-sample-project/src/main/kotlin/project/Main.kt
src/main/resources/version-config-e2e.json

Resolves: None
Splitting providers into those that can be run on default GH runners on those that require custom runners with extra RAM ([here](https://github.com/VirtuslabRnD/pulumi-kotlin/pull/708)) lead to some issues with the release pipeline, specifically with the installation of Rclone (due to missing gh, zip, and wget dependencies). In the future this can be addressed in our VM startup script, but I didn't want to mess with it right now.

Fix release workflow

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
It looks like the 8 GB of RAM is not sufficient, the build is flaky: https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/11418790179/job/31772643392

Move GitLab to self-hosted runner

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml

Resolves: None
This mitigates the following compilation error:
```
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during psi2ir
File being compiled: (672,9) in /root/_work/pulumi-kotlin/pulumi-kotlin/build/generated-src/gitlab8/com/pulumi/gitlab/kotlin/ApplicationSettingsArgs.kt
The root cause java.lang.StackOverflowError was thrown at: java.base/java.lang.ClassLoader.defineClass1(Native Method)
null: KtDotQualifiedExpression:
com.pulumi.gitlab.ApplicationSettingsArgs.builder()
.abuseNotificationEmail(abuseNotificationEmail?.applyValue({ args0 -> args0 }))
.adminMode(adminMode?.applyValue({ args0 -> args0 }))
.afterSignOutPath(afterSignOutPath?.applyValue({ args0 -> args0 }))
.afterSignUpText(afterSignUpText?.applyValue({ args0 -> args0 })) …
```

Update -Xss value

---

.github/workflows/update_schemas.yml

Resolves: None
Let's not waste resources on releases with a single provider. If we do it every other day, there's a better chance of having several providers released at once.

Switch release cron to every other day

---

.github/workflows/update_schemas.yml

Resolves: None
This updates the release cron expression to run daily between Monday and Friday. After the changes done in https://github.com/VirtuslabRnD/pulumi-kotlin/pull/829, we will no longer open a release PR unless 5 providers are updated in it, which will help limit the number of GH Actions job - there is no need to run it every other day anymore.

Update release cron

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
src/main/resources/version-config.json

Resolves: None
Cloudflare v6 and Azure Native v3 can be added.

Add Cloudflare and Azure Native majors

---

.github/workflows/prepare_release.yml
.github/workflows/publish_to_maven_local.yml
src/main/kotlin/org/virtuslab/pulumikotlin/codegen/utils/Constants.kt

Resolves: None
https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/14478274216/job/40614820196
The Cloudflare provider had to be moved to a self-hosted runner due to memory issues. This Azure Native fix is a temporary workaround until https://github.com/pulumi/pulumi-azure-native/issues/4107 is fixed.

Fix azure-native code generation
